### PR TITLE
feat: add more js repos

### PR DESCRIPTION
**Pull request by achingbrain**
Adds a few more repos that are using unified CI

### CODE REVIEW

**Review by galargh — APPROVED** [review]

**Comment by galargh** [comment]
@achingbrain FYI, these 3 didn't get merged because of build/test failures:
- https://github.com/libp2p/js-libp2p-delegated-peer-routing/pull/69
- https://github.com/ipfs/js-ipfs-bitswap/pull/432
- https://github.com/ipfs/aegir/pull/982

I pulled the failure reasons out of logs and posted them as comments in the PRs.

**Comment by achingbrain** [comment]
Those errors have since been fixed in master - is it possible to automatically rebase the web3-bot PRs when the HEAD of master changes?

**Comment by marten-seemann** [comment]
> Those errors have since been fixed in master (for the most part) - is it possible to automatically rebase the web3-bot PRs when the HEAD of master changes?

Unfortunately GitHub doesn't have any option for that. You need to rebase manually :(

**Comment by achingbrain** [comment]
Is there no way to do it in a similar way to dependabot?  You can type `@depdendabot rebase` as a comment in a dependabot issue and it'll do the rebase automagically.

**Comment by galargh** [comment]
Created an issue here to explore this: https://github.com/protocol/.github/issues/339

I think both are achievable through yet another Actions workflow but I'd need to do more research to know which one could be less intrusive (i.e. how could we limit it to be triggered only on web3-bot's PRs).

**Pull request merged**
