### PR TITLE
chore: remove go-ds-crdt

### PR DESCRIPTION
**Pull request by hsanjuan**
Sorry, the release flow that was enabled replaces a "git tag; git push" operation, which takes me 1 second, with a PR, a 40 minute build and maintenance of a file with redundant information. And it does not generate an automatic changelog based on commit messages or publish a github release as I expected so it literally takes 0 work from me. All this is just adding crust that costs me time. I will re-enable this project when this changes.

### CODE REVIEW

**Comment by Stebalien** [comment]
The goal of the release flow is to check the version number against semver. Basically, it catches breaking changes in patch releases.

Unfortunately, GitHub doesn't have any way to run these checks pre-release/tag. I agree that the new flow is really annoying, but if it's a 40 minute thing, CI is likely taking too long anyways.

**Comment by marten-seemann** [comment]
> it does not generate an automatic changelog based on commit messages or publish a github release as I expected so it literally takes 0 work from me

That's actually something we're working on (see #228), and will be rolled out in the next iteration of the workflows.
As @Stebalien points out, these new workflows prevent us from messing up semver (as we've done countless times in the past!).

**Comment by hsanjuan** [comment]
This is all very useful in general.

But since this was introduced I have lost a lot of time.  The CI runs 6 or 8 jobs and not being able to do it in parallel makes it 40 minutes total time. The CI wants to run all tests together and is unable to adapt to the project (separate datastore suite from local tests). At first it was mis-configured to the point tests failed because they took longer than expected. I lost a lot of time trying to explain how this is 0 help as I'm actively maintaining the project and it already has the tests it needs.

But I still left it around in the end. Now release-management has been introduced, something I never needed nor asked for. I have tried it and discovered it makes me lose more time and does not help me.

I am not arguing that these unified CI is unhelpful or not needed in general, I am trying to argue that it is getting my way, repeatedly, for this project in particular at this point in time. I babysit 3 or 4 other small repos where I don't mind it. I don't understand what is so hard to accept that this project, by what it is, by what it tests, by how it is maintained right now, may constitute an exception to the unified CI and perhaps it is not the end of the world if we do not blanket-roll it over it, specially after the maintainer requests it.

Can we please grant the exception?

**Review by marten-seemann — APPROVED** [review]
Fair point. Thank you for elaborating @hsanjuan, and sorry that this took so long.

Unified CI is supposed to make maintainers' life easier, not the other way around. If at any point in the future you feel like you want to reenable the workflows, feel free to open a PR here. @galargh has been working on decoupling the testing workflows from the versioning workflows, so very soon it will also be possible to just opt-in into one of them.

**Comment by hsanjuan** [comment]
> so very soon it will also be possible to just opt-in into one of them.

Thank you, happy re-opting into the testing then.

**Pull request merged**
