### PR TITLE
only run gofmt and go mod tidy on initial deployment

### LINKED ISSUE #110: normal deploy shouldn't run go mod tidy and gofmt
When merging https://github.com/protocol/.github/pull/109, which just added go-bitfield, the workflow also opened https://github.com/ipld/go-ipld-graphql/pull/30.
We should only run `go mod tidy` and `gofmt` on initial deployment.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #110.

### CODE REVIEW

**Comment by mvdan** [comment]
I don't get this. We want modules to remain tidy, and code to remain gofmt-ed, so as far as I can tell the previous logic was right.

**Comment by mvdan** [comment]
Thinking about it again, I guess we want tidy+gofmt to be CI checks, not automated PR shenanigans. It's best if a PR gets fixed to follow gofmt, rather than merging it into master and immediately after have a "fix gofmt" automated commit be merged.

**Comment by marten-seemann** [comment]
> Thinking about it again, I guess we want tidy+gofmt to be CI checks, not automated PR shenanigans. It's best if a PR gets fixed to follow gofmt, rather than merging it into master and immediately after have a "fix gofmt" automated commit be merged.

Exactly, that's why tidy and gofmt are already part of the check workflow. I haven't researched how the graphql got out of sync, but this shouldn't be allowed to happen, unless someone merges a PR for which CI failed.

**Comment by mvdan** [comment]
Indeed, it seems someone pushed straight to master and broke the check workflow: https://github.com/ipld/go-ipld-graphql/commit/402a472355ba36cd9bfb40df60cd9c8ea261e07d

SGTM

**Review by mvdan — APPROVED** [review]

**Comment by marten-seemann** [comment]
Looks like I forgot to merge this PR. Rebased and updated.

**Pull request merged**
