### PR TITLE
disable pubsub integration

### PR DESCRIPTION
**Pull request by vyzo**

### CODE REVIEW

**Comment by marten-seemann** [comment]
Why?

**Comment by vyzo** [comment]
It didn't work and we setup CircleCi.

**Comment by marten-seemann** [comment]
Just leave it in here. Fix is in progress.

**Comment by vyzo** [comment]
Please remove this repo; the tests can't run there and it is making a ton of work for ourselves.
We are fine with CircleCI.

**Comment by marten-seemann** [comment]
Can we fix the tests? This workflow isn’t doing anything out of the ordinary, just super basic go test, go vet and staticcheck.

**Comment by vyzo** [comment]
there is nothing wrong with the tests; they run fine and pass locally, in
circle, and previously travis.

**Comment by vyzo** [comment]
also note that they are a little on the h3avy side, lots of goroutines and
fike descriptors, but this is by necessity,

**Review by marten-seemann — APPROVED** [review]
Given the demanding resource requirements for `go test` in pubsub, I think it makes sense to disable it for now.

@coryschwartz did a clean-up of the code and fixed all the `go vet` and `staticcheck` errors, and I've rebased his PR so that we can get those fixes in in https://github.com/libp2p/go-libp2p-pubsub/pull/417.

**Pull request merged**
