### PR TITLE
adding eudico to CI

### PR DESCRIPTION
**Pull request by adlrocha**
Adding https://github.com/filecoin-project/eudico/

### CODE REVIEW

**Review by galargh — APPROVED** [review]

**Comment by galargh** [comment]
Please make sure `web3-bot` has write access to the repository before a merge.

**Comment by adlrocha** [comment]
It already has permissions, we should be ready to merge :) Thanks!

**Comment by adlrocha** [comment]
Quick question @galargh, how much time does it take for the CI config to be propagated to the repo? Thanks!

**Comment by galargh** [comment]
@adlrocha If everything goes well under an hour but there are some issues with deploy to `eudico` - see https://github.com/protocol/.github/runs/5880463824?check_suite_focus=true

Upgrading `quantile` to a version which has this fix in - https://github.com/streadway/quantile/pull/8 - should enable Unified CI deploy.

**Comment by adlrocha** [comment]
hey @galargh, sorry to bother you again. I upgraded `quantile` and tried to re-run the job and got the following: https://github.com/protocol/.github/runs/5966861525?check_suite_focus=true

This repo is a fork of Lotus, and I am starting to think it may not be suitable for common CI integration and we may need to configure the CI pipeline directly in Circle CI. Thoughts on this? Thanks!

**Comment by galargh** [comment]
I'm afraid `eudico` is affected by this issue: https://github.com/protocol/.github/issues/248

Unfortunately, right now Unified CI cannot be doployed to repos that use submodules. Let's revert this then.

**Comment by adlrocha** [comment]
Too bad. Thank you for your support @galargh

**Pull request merged**
