### PR TITLE
add ipfs repos to unified ci

### PR DESCRIPTION
**Pull request by achingbrain**
These repos all have the shiny new auto-deploy scripts so should be managed by `web3-bot`.

### CODE REVIEW

**Comment by achingbrain** [comment]
@galargh Do I need to do anything else to get these repos under unified-ci or is just adding them to this config file enough?

**Review by galargh — APPROVED** [review]

**Comment by galargh** [comment]
That's it - as long as web3-bot is allowed to write to them :)

**Comment by achingbrain** [comment]
I can't merge this branch as I have no perms.  @galargh @marten-seemann can one of you do it?

**Comment by achingbrain** [comment]
Also, maybe you could give me perms?

**Pull request merged**
