### PR TITLE
update the Codecov Action to v2.0.1

### PR DESCRIPTION
**Pull request by marten-seemann**
Codecov has a new uploader (again!).
Aren't we all happy about new Codecov uploaders?

### CODE REVIEW

**Review by mvdan — APPROVED** [review]
Any changes relevant to us?

**Comment by marten-seemann** [comment]
These are the release notes: https://github.com/codecov/codecov-action/releases/tag/v2.0.0. Looks like they're going to deprecate their v1 uploader early next year. Not sure how this is related to the breach they had a few months ago, they claim they now checksum and verify their uploader script and everything will be secure (this time for real!!111).

**Comment by mvdan** [comment]
Ah, sounds good. Given that deprecation window, we want to upgrade sooner than later, then.

**Comment by marten-seemann** [comment]
I was planning to hold back this PR (as well as #139) until we upgrade to Go 1.17, in order to reduce the noise created by deploying to ~140 repos.

**Pull request merged**
